# Generated by Django 5.2.1 on 2026-05-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='percentage',
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.CharField(default='beginner', max_length=100),
        ),
    ]
