# Generated by Django 5.2.1 on 2026-05-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_techstack_delete_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='techstack',
            name='description',
            field=models.CharField(default='None', max_length=150),
        ),
    ]
